### ISSUE TITLE
蓝色棋子

### ISSUE THREAD

**Issue by kaixinsoft** [wickila/autotrade#1]
## 功能不错，之前也给同学做了一个分销的插件，不过很定制化，主要是为了方便下单。

没有具体的看，也没有实际的运行，这里是不是应该是“蓝色旗子”
<li>点击”开始标记“按钮，小助手将把已选订单自动标记为蓝色棋子，并且标记为”已采购@by auto_trade“</li>

**Comment by wickila** [comment]
谢谢指正。下个版本提交的时候修改好。
